name: disperse_env
channels:
  - defaults
  - astropy
  - conda-forge
dependencies:
  - python=3.8
  - numpy
  - scipy
  - matplotlib
  - astropy>=4.1
  - specutils>=1.2
  - astroquery
  - tqdm
  - pandas
  - jupyter
  - ipython
  - lightkurve
  - bokeh<2.3
  - seaborn
  - scikit-learn
  - pyarrow
  - pytest
  - pip
  - sphinx
  - black
  - pip:
      - recommonmark
      - emcee
      - corner
